version: '3'
services:
  pheg:
    image: usipcomdevteam/pheg
    build: .
    volumes:
      - ".:/app"
      - "${HOME}/.ssh:/root/.ssh"
      - "${PWD}/../docker/volumes/composer/auth.json:/root/.composer/auth.json"
    working_dir: /app
    command: composer install --ignore-platform-req=ext-apache
    # command: tail -f /dev/null
