<?php declare(strict_types=1);

/**
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

namespace Simtabi\Pheg\Toolbox\Intel\Info\Os\Contracts;

interface OsInfoInterface
{
    public function arch(): string;

    public function family(): string;

    public function hostname(): string;

    public function isApple(): bool;

    public function isBSD(): bool;

    /**
     * @param int|string $family
     */
    public function isFamily(int|string $family): bool;

    /**
     * @param int|string $os
     */
    public function isOs($os): bool;

    public function isUnix(): bool;

    public function isWindows(): bool;

    public function os(): string;

    /**
     * Register new constants.
     */
    public function register(): void;

    public function release(): string;

    /**
     * Get a unique ID for the host machine.
     *
     * Conforms to UUIDs generated by sebhildebrandt/systeminformation.
     *
     * @see https://github.com/sebhildebrandt/systeminformation/blob/master/lib/osinfo.js
     *
     * @return string|null
     *   The machine UUID.
     */
    public function uuid(): ?string;

    public function version(): string;
}
